@echo off
@rem ##########################################################################
@rem
@rem  Gradle startup script for Windows
@rem  This file is auto-generated by `gradle wrapper` and should not be modified
@rem  except for comments or JVM options. It bootstraps Gradle by invoking
@rem  gradle/wrapper/gradle-wrapper.jar with the correct Java runtime.
@rem
@rem ##########################################################################

@rem Set local scope for variables with Windows NT shell
if "%OS%"=="Windows_NT" setlocal

set DIRNAME=%~dp0
if "%DIRNAME%"=="" set DIRNAME=.
set APP_BASE_NAME=%~n0
set APP_HOME=%DIRNAME%

@rem Default JVM options (can be overridden via JAVA_OPTS or GRADLE_OPTS)
set DEFAULT_JVM_OPTS=

@rem Locate Java
if defined JAVA_HOME goto findJavaFromJavaHome

set JAVA_EXE=java.exe
%JAVA_EXE% -version >NUL 2>&1
if "%ERRORLEVEL%"=="0" goto init

echo.
echo ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
echo Please set JAVA_HOME to the location of your Java installation.
goto fail

:findJavaFromJavaHome
set JAVA_HOME=%JAVA_HOME:"=%
set JAVA_EXE=%JAVA_HOME%/bin/java.exe
if exist "%JAVA_EXE%" goto init

echo.
echo ERROR: JAVA_HOME is set to an invalid directory: %JAVA_HOME%
echo Please set JAVA_HOME to the location of your Java installation.
goto fail

:init
@rem Collect command-line arguments
set CMD_LINE_ARGS=%*

@rem Setup classpath to Gradle wrapper JAR
set CLASSPATH=%APP_HOME%\gradle\wrapper\gradle-wrapper.jar

@rem Execute Gradle
"%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %GRADLE_OPTS% ^
  "-Dorg.gradle.appname=%APP_BASE_NAME%" ^
  -classpath "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %CMD_LINE_ARGS%

:end
@rem End local scope for Windows NT shell
if "%ERRORLEVEL%"=="0" goto mainEnd

:fail
@rem Return error code
if not ""=="%GRADLE_EXIT_CONSOLE%" exit 1
exit /b 1

:mainEnd
if "%OS%"=="Windows_NT" endlocal
